# Generated by Django 4.0.3 on 2022-12-08 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_remove_salesrecord_customer_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='import_href',
        ),
    ]
