# Generated by Django 4.0.3 on 2022-12-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_remove_automobilevo_import_href'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesperson',
            old_name='sales_person_name',
            new_name='salesperson_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_number',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='price',
        ),
    ]
