# Generated by Django 4.0.3 on 2022-12-08 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_rename_sales_person_name_salesperson_salesperson_name_and_more'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='salesperson',
        #     old_name='sales_person_name',
        #     new_name='salesperson_name',
        # ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='sales_record_number',
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='automobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vins', to='sales_rest.automobilevo'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_names', to='sales_rest.customer'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='salesperson_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesperson_names', to='sales_rest.salesperson'),
        ),
    ]
