# Generated by Django 4.0.3 on 2022-12-09 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0012_alter_salesrecord_employee_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecord',
            name='employee_number',
        ),
    ]
