# Generated by Django 4.0.3 on 2022-12-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0013_remove_salesrecord_employee_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesrecord',
            old_name='automobile',
            new_name='vin',
        ),
    ]
