# Generated by Django 4.0.3 on 2022-12-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0016_alter_salesrecord_employee_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesrecord',
            old_name='vin',
            new_name='automobile',
        ),
        migrations.RenameField(
            model_name='salesrecord',
            old_name='customer_name',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='salesrecord',
            old_name='salesperson_name',
            new_name='salesperson',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='employee_number',
        ),
    ]
