# Generated by Django 4.0.3 on 2022-12-12 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0018_alter_salesrecord_automobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sales_rest.salesperson'),
        ),
    ]
