# Generated by Django 4.0.3 on 2022-12-12 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0020_alter_automobilevo_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sales_rest.customer'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
