# Generated by Django 4.0.3 on 2022-12-12 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0020_alter_automobilevo_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecord',
            name='price',
        ),
    ]
