# Generated by Django 4.0.3 on 2022-12-13 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0021_alter_salesrecord_customer_alter_salesrecord_price'),
        ('sales_rest', '0022_salesrecord_price'),
    ]

    operations = [
    ]
