# Generated by Django 4.0.3 on 2022-12-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_appointment_vin_alter_automobilevo_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='import_href',
        ),
    ]
