# Generated by Django 4.0.3 on 2022-12-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_remove_automobilevo_import_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
