# Generated by Django 4.0.3 on 2022-12-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_appointment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobilevo',
            options={'verbose_name': 'Automobile'},
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='import_href',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
