# Generated by Django 4.0.3 on 2022-12-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_remove_appointment_status_appointment_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
